# Generated by Django 3.0.3 on 2020-08-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dogNamesList',
            field=models.CharField(choices=[('Izy', 'izy')], default='', max_length=60),
        ),
    ]
