# Generated by Django 3.0.3 on 2020-08-03 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_dognameslist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='picture',
            new_name='postPicture',
        ),
    ]
