# Generated by Django 3.0.3 on 2020-08-10 09:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
import dogs.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_auto_20200802_2134'),
        ('posts', '0004_auto_20200804_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dog',
            field=models.ForeignKey(choices=[(dogs.models.Dog(uuid.UUID('cef0cbf3-6458-4f13-a418-ee4d7e7505cd'), 'Izy', 'Croisé Berger', datetime.date(2019, 2, 1), datetime.date(2019, 5, 16), 'Noir, Feux, Blanc', 'Petite queue mais pas coupée, doubles ergots aux pattes arrière', None, 1, None, False, True, False, False, False, '12301', '', 'F', 'medium', None, True, 'izy12301.jpg'), dogs.models.Dog(uuid.UUID('cef0cbf3-6458-4f13-a418-ee4d7e7505cd'), 'Izy', 'Croisé Berger', datetime.date(2019, 2, 1), datetime.date(2019, 5, 16), 'Noir, Feux, Blanc', 'Petite queue mais pas coupée, doubles ergots aux pattes arrière', None, 1, None, False, True, False, False, False, '12301', '', 'F', 'medium', None, True, 'izy12301.jpg'))], default='', on_delete=django.db.models.deletion.CASCADE, related_name='dogPost', to='dogs.Dog'),
        ),
    ]
