# Generated by Django 3.0.3 on 2020-07-17 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('idDog', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('dogBreed', models.CharField(max_length=50)),
                ('birthDate', models.DateField()),
                ('arrivalDate', models.DateField()),
                ('dogCoat', models.CharField(max_length=50)),
                ('recognitionSigns', models.CharField(max_length=250)),
                ('hosted', models.BooleanField(default=False)),
                ('adopted', models.BooleanField(default=False)),
                ('sponsored', models.BooleanField(default=False)),
                ('hasHostDemand', models.BooleanField(default=False)),
                ('hasAdoptionDemand', models.BooleanField(default=False)),
                ('chipId', models.CharField(max_length=5, unique=True)),
                ('story', models.TextField(default='', max_length=500)),
                ('sex', models.CharField(choices=[('F', 'Femelle'), ('M', 'Mâle'), ('other', 'Autre')], default='F', max_length=7)),
                ('size', models.CharField(choices=[('small', 'Petit.e'), ('medium', 'Moyen.ne'), ('big', 'Grand.e')], default='small', max_length=8)),
                ('serology', models.BooleanField(null=True)),
                ('rabiesVaccines', models.BooleanField(default=False)),
                ('picture', models.ImageField(blank=True, default='defaultDog.png', upload_to='')),
                ('hostFamily', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hostedDog', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adoptedDog', to=settings.AUTH_USER_MODEL)),
                ('sponsor', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsoredDog', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
