# Generated by Django 3.0.3 on 2020-08-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isHost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='isOwner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='isSponsor',
            field=models.BooleanField(default=False),
        ),
    ]
