# Generated by Django 3.0.3 on 2020-07-17 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demandDate', models.DateField(auto_now_add=True, verbose_name='date de création')),
                ('demandType', models.CharField(max_length=8)),
                ('applicant', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandApplicant', to=settings.AUTH_USER_MODEL)),
                ('dog', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandDog', to='dogs.Dog')),
            ],
        ),
    ]
